### ISSUE TITLE
Remove express dependency

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#100]
**Is your feature request related to a problem? Please describe.**
Currently the bot integrates a super small express app, which was added to support waking up the bot in heroku. This is no longer needed.

**Describe the solution you'd like**
Remove the express code, and dependencies.

**Additional context**
We can always add the express server back if needed.

**Comment by JoshQuaintance** [comment]
I'll take care of this
