### ISSUE TITLE
[Bug] Issues with reaction based formatting if the message isn't a programming language

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#101]
**Describe the bug**
Currently with the bot if a given message isn't recognized as a language, the bot explodes, and **removes all emojis on the given message**. This technically is 2 problems.

**To Reproduce**
1. Create a message that wont format to any given language, example: `%%%`
2. Add a random reaction and then use the "robot" reaction on said message
3. Observe all previous reactions disappear, and the bot will error out.

**Expected behavior**
Existing reactions should stay, **and** the bot should return the given message, just without any formatting.

**Additional context**
This seems to be partially fixed with a check in the `isSupportedByPrettier` function to make sure the `languageName` is defined. As the error occurs due to that param being undefined.

The other issue is not all emojis should be removed.

**Comment by cjcanlas01** [comment]
Regarding the issue that not all emojis should be removed. I think modifying this part:

https://github.com/bradtaniguchi/discord-bot-test/blob/d7c20b3b1244e70c04ec06a79846b6c4e8cca8d5/src/commands/bootstrap.ts#L43

To something like this should get the job done:

https://github.com/bradtaniguchi/discord-bot-test/blob/d7c20b3b1244e70c04ec06a79846b6c4e8cca8d5/src/commands/bootstrap.ts#L79
