### ISSUE TITLE
[CHORE] Update hosting providers, otherwise no bot for the rest of july

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#118]
**What needs to be done**
I got an email about running out of dyno hours on heroku for the rest of july. So the bot currently wont "run" until next month

**Additional context**
I'll check out more free tier hosting options. Otherwise I'll have to add a credit card to get more hours on heroku (which I honestly don't want to do)

**Comment by naomi-lgbt** [comment]
It looks like there is the option to host it on repl.it and use Uptime Robot (which is apparently free?) to ping it and keep it from sleeping.

**Comment by bradtaniguchi** [comment]
I'm not a big fan of using "uptime" stuff, since it essentially just spams the hosting provider who is giving a free tier in the first place. 

If we were to use this, we could just keep using heroku. 

There might be a middle ground, where we stay on heroku, but move it back to the web-service option with express. We'd end up back where we wanted to find a way to get the bot to "wake" before using it in discord, which might be good enough, since we don't really test that often (or really ever) in discord this should be fine for the short term.

One option is to leverage tooling in the repo itself to "wake" the bot locally if we want to test it in the actual discord server. Otherwise we would just use whatever tooling we use right now to run it where-ever 🤔

**Comment by naomi-lgbt** [comment]
In that case, I believe Heroku has the ability to just switch the Dyno off. So we could leave the bot off, and switch it on when we're actively testing or demonstrating the MVP. 🙂

**Comment by Ryuno-Ki** [comment]
What about asking @QuincyLarson to contact Heroku?
Who knows? Perhaps they could grant a larger dyno for freeCodeCamp?

**Comment by bradtaniguchi** [comment]
@Ryuno-Ki I'd rather not get Quincy involved until we get going with the official bot. Right now the current bot is still 'unofficial', so hosting and testing it isn't to big of a deal. Once we are working and using the official bot, having more serious infrastructure will become more important. Till then we can scrounge up some free option somwhere ;D

**Comment by bradtaniguchi** [comment]
I might just add a CC to heroku and deal with it XD. Might give me more incentive to host something else on heroku. Best not to freeload on their free services to much. I'll close this for now and will probably just continue personally supporting the bot on heroku by adding a CC. AFAIK I don't get charged anyways :)
