### ISSUE TITLE
[FEATURE/CHORE] Update console log statements to a logger

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#119]
**Is your feature request related to a problem? Please describe.**
Right now all logs are handled by `console.log` or similar.

**Describe the solution you'd like**
We should migrate all of these calls to using something like [winston](https://github.com/winstonjs/winston). This will allow us to be more flexible while logging and getting more context. (such as information on who did what)

**Describe alternatives you've considered**
We can stick with our current logging system, but it doesn't scale or give enough context often.

**Additional context**
This process should be done slowly, and can be spread across multiple PR requests.

**Comment by JoshQuaintance** [comment]
I will start by installing winston as a dependency, then I will go through the docs see what I can do.

**Comment by JoshQuaintance** [comment]
So, I've been tinkering around with winston, and it seems like we can make the logger log in a json format, or in a format that we can configure ourselves.

**Comment by naomi-lgbt** [comment]
@JoshuaPelealu Where are you at with this?

@bradtaniguchi I have been thinking - at least some of these console logs should probably be migrated to end-user messages. Otherwise we face the struggle of the bot appearing to be unresponsive, instead of providing feedback to the user about why the command didn't work.

**Comment by bradtaniguchi** [comment]
@nhcarrigan I think we can update some error states to generic end user messages, **and** still log with more extensive logging information.


Also, I'll start looking into this :)
