### ISSUE TITLE
[FEATURE] Update Help command to be able to take parameters and a nicer help message

### ISSUE THREAD

**Issue by JoshQuaintance** [freeCodeCamp/CamperChan-discord#120]
**Is your feature request related to a problem? Please describe.**
Right now the help command only sends a message to the user and send the channel a message notifying that a help message was sent.

**Describe the solution you'd like**
We can improve this so that the command will be able to take a parameter to a command, and reply with the command name, description, and how to use it. We can also give every command a parameter where we can specify how to use each command.

**Describe alternatives you've considered**
We can at least make the help command instead of sending such a long list with description, just send a comma seperated list of all the commands into the channel the user is using it at. Then they can use the `help [command]` feature to find out more about each command

**Additional context**
This will make the help statemenet for the bot be a lot cleaner and nicer, that the user can use easily.

**Comment by naomi-lgbt** [comment]
I like the idea of adding a parameter to the help command. 

Not sure how I feel about sending a comma separated list instead of an embed, though - that feels a lot less elegant and clean.

**Comment by JoshQuaintance** [comment]
Did I accidentally assigned you both, or is that an automatic process?

**Comment by naomi-lgbt** [comment]
That is an automatic process 🙂

**Comment by JoshQuaintance** [comment]
What I meant by a comma seperated list is more of something like this:
![image](https://user-images.githubusercontent.com/45566099/89106515-78304180-d3f8-11ea-93cf-71de3564ad6e.png)

And the parameters would look something like this:
![image](https://user-images.githubusercontent.com/45566099/89106680-c3971f80-d3f9-11ea-85eb-6ee0a2d233da.png)

**Comment by bradtaniguchi** [comment]
I like this idea, where the first `help` command returns just the list of commands. But you need to call the bot with `<prefix> help <name of command>`  to get help for a specific command.

I'm not sure about providing information beyond just 1 command though. Most "help" utilities support 1 and only 1 command at a time. Examples like `man`, or `--help` flags on most of the CLI utilities all are used just for 1 command. This should be fine :)

**Comment by JoshQuaintance** [comment]
What do you mean supporting beyond just 1 command? It can only serve 1 command at a time.

**Comment by bradtaniguchi** [comment]
I mis-read the original post, and thought you could ask for multiple commands at the same time. Sorry :)

**Comment by JoshuaPelealu** [comment]
![image](https://user-images.githubusercontent.com/45566099/89108628-f2b48d80-d407-11ea-82b0-4b98c4f5355b.png)
For this part, we might make another command that will give an info about the bot

**Comment by JoshQuaintance** [comment]
I'm going to refactor most of the description for the commands to be a little more descriptive. This will be on a different PR.
