### ISSUE TITLE
[CHORE] Add more badges to README

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#125]
**What needs to be done**
Nothing, but this is cool :P

Adding some badges, similar to the current travis-ci one shouldn't be hard, and don't necessarily have to be "useful". Sites like https://shields.io/ can be used, or get badges from more "official" sources. If possible I'd like to have all of them follow the current format of the existing travis-ci badge though :)

**Additional context**
Please ask here before opening any PRs to add them :)

**Comment by naomi-lgbt** [comment]
Here are some ideas:
- Adding the LGTM integration will give us a code quality badge and an alerts badge 
- I can enable widgets on the bot test server and we can have a Discord badge
- Dependabot Badge
- Version badge
- License badge
- GitHub Issues/PR badges

**Comment by bradtaniguchi** [comment]
How complex are each of these?

**Comment by naomi-lgbt** [comment]
The LGTM integration is the only complex one. 

The rest I could add in a PR real quick.

**Comment by bradtaniguchi** [comment]
So just the LGTM integration isn't added yet right after this PR: #127 

The integration is available here right:
https://github.com/marketplace/lgtm

I have dependabot on a few other repos, so I'll look back on how to add it again

**Comment by naomi-lgbt** [comment]
Yep - LGTM (which I set up through the [website](https://lgtm.com/)) and Dependabot are the only ones missing.

**Comment by Twaha-Rahman** [comment]
Maybe add a `Gitpod` badge? It could take the user to the Gitpod of the repo on click. Plus it's quite easy to set up, just add this line -

`[![Setup Automated](https://img.shields.io/badge/setup-automated-blue?logo=gitpod)](https://gitpod.io/from-referrer/)`

It'll look like this -> [![Setup Automated](https://img.shields.io/badge/setup-automated-blue?logo=gitpod)](https://gitpod.io/from-referrer/)
