### ISSUE TITLE
[FEATURE] Update suspend command to provide more resources and information

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#135]
**Is your feature request related to a problem? Please describe.**
Currently the `suspend` command provides the following:
![image](https://user-images.githubusercontent.com/10079147/90065014-75f3a000-dca0-11ea-9435-9dda20665e7e.png)
We should provide more information in this message, to the user for their suspending, as the bot is a "third party" it can act as a moderator to make the user more aware of the situation rather than the traditional DM from the actual mod who performed the suspension.

**Describe the solution you'd like**
We should provide the actual moderation template instead. (as suggested by @nhcarrigan)

**Describe alternatives you've considered**
We could also add more "sub-commands" available to the bot within a `suspended channel` if need be in the future :)

**Additional context**
TODO: add moderation template link here, or hopefully someone else does below :)

**Comment by naomi-lgbt** [comment]
This should be good now, with the merge of #138?

**Comment by bradtaniguchi** [comment]
Yea we can close this for now
