### ISSUE TITLE
[CHORE] Update social media preview

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#136]
**What needs to be done**
Currently when posting links to stuff in this repo, the social media preview is a picture of my profile by default. This should be changed to **anything** else. I'd rather not use a direct FCC icon, as this **isn't** the official bot. 

**Additional context**
I was thinking maybe a simple picture of the bot itself working, or some random "robot" stock photo. Could also be a "joke" picture for cookies/brownies or something haha

**Comment by bradtaniguchi** [comment]
If someone has a picture suggestion let me know, otherwise I need to add it to the repo settings

**Comment by naomi-lgbt** [comment]
Octocat! 

Or space!
![image](https://user-images.githubusercontent.com/63889819/90072626-9d506a00-dcac-11ea-8121-0a5d506f5b20.png)

**Comment by bradtaniguchi** [comment]
I'm a fan of space stuff, a custom octocat might be on the table.

I'll look at some stock photos of robots or something as an alternative haha

**Comment by bradtaniguchi** [comment]
Maybe:
![everyday-basics-pi9W2dWDdak-unsplash](https://user-images.githubusercontent.com/10079147/90185959-4e6a0980-dd6c-11ea-8f07-76c43dc14b60.jpg)


link:
https://unsplash.com/photos/pi9W2dWDdak

**Comment by naomi-lgbt** [comment]
Oh that one's cute. I like it!

**Comment by bradtaniguchi** [comment]
going with the robot for now, if we have another suggestion we can change it later :)
