### ISSUE TITLE
[FEATURE] Update discord-bot close command, and add another similar command

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#139]
**Is your feature request related to a problem? Please describe.**
It was suggested to supporting different "moderation flows" changing the `close` command available only in a "suspended" channel

**Describe the solution you'd like**

```
FCC accepted @mention - Remove suspension and close the channel
FCC denied @mention - Leave the suspension in place and only close the channel (moderator must manually ban the user to prevent risks of the bot going rogue)
```

**Additional context**
Related #137

**Comment by naomi-lgbt** [comment]
This should be good now, with the merge of #138?

**Comment by bradtaniguchi** [comment]
Just got more feedback about the flow being:
```markdown
1. Moderater does command: !FCC suspend <@userID> <reason> inside #bot-text (for now)
- The bot suspends the mentioned user
- The bot creates a separate channel for the user and all moderators
- The bot sends a message in that channel tagging both the user and the moderator group

2. From there on out Moderators can talk with the user. Depending on how the conversation goes, the moderator can do:
a. !FCC close accepted <@mention>
b. !FCC close denied <@mention>

3. The bot will send a summery to #mod-log
```

If this isn't whats going on, we can keep this issue open and use it as a reference to updating the existing flow. I think the commands in step 2 changed?

**Comment by naomi-lgbt** [comment]
This is the current flow. :D

**Comment by bradtaniguchi** [comment]
ok cool, so it thats what we got I'll close this :)
