### ISSUE TITLE
[FEATURE] Update logging format for heroku

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#143]
**Is your feature request related to a problem? Please describe.**
With the current `console.log` things will be hard to debug if there are multiple calls going on at the same time due to the log messages lacking any kind of meta-data.

**Describe the solution you'd like**
After #119 we should update the format to include the following:
- messageId/reactionId(?)
- user who performed the action
- update format to something that easily "searchable" and "filterable", maybe `json` or otherwise. This is due to
heroku not really providing any logging tools.

These 2 things **should** allow us

**Describe alternatives you've considered**
We could also use some other service to handle logs, and use winston as the "abstraction layer". Regardless we will want to have this meta-data passed to the log statements before hand.

**Additional context**
See winston format documentation:
https://github.com/winstonjs/winston#formats

**Comment by kaiwalyakoparkar** [comment]
Hey, @bradtaniguchi / @nhcarrigan I would like to work on this. Could you please guide me?

**Comment by naomi-lgbt** [comment]
Heya @kaiwalyakoparkar,

Thanks for your interest in this issue. At the moment, I need to do some investigating to see which parts of this are still needed (the bot is no longer deployed on Heroku, for example).

I'm going to remove the `good first issue` label for the time being, but once I have a better understanding of how we want to approach this task, I'll reach out to you and get you set up to contribute 🙂

**Comment by kaiwalyakoparkar** [comment]
Thank you so much @nhcarrigan. Is there any other issue in other fcc repos I can do my first contribution to?

**Comment by naomi-lgbt** [comment]
I don't know of any off hand, unfortunately. Worth keeping an eye on our main repository, where most of our issues are tracked - you can watch for `first timers only` issues there 🙂

**Comment by bradtaniguchi** [comment]
@nhcarrigan we can close this issue, since it isn't applicable anymore.
