### ISSUE TITLE
[FEATURE/DISCUSSION] Start working on "userlog" feature for admins

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#152]
**Is your feature request related to a problem? Please describe.**
Currently moderation on the discord server doesn't provide any way to make "notes" or save references about a user's behavior. 

**Describe the solution you'd like**
Add a new `userlog` command based off the following examples:
```
fCC userlog @bradtaniguchi User was suspended for advertising (bot saves link to this message)
fCC userlog @bradtaniguchi User was suspended again, this time for disruptive behavior (bot saves link to this message)
```
so:
```
fCC userlog <user> <...rich text message>
```

This will require updates to the database to save the `userId` mentioned, **and** their current username, along with other meta data. (we can talk about the database schema) Any discord links should be saved as-is to be displayed later

**Describe alternatives you've considered**
We could add another command that can be used to "read" this information later, or use the same command without the third argument. Regardless of how the "read" is called, it should show these logs, previous suspensions and their username (as these can be changed)

**Additional context**
This feature will require the usage of the mongodb database, and probably some database updates overall so user's are changed.

**Comment by naomi-lgbt** [comment]
So here's what I'm thinking: 
If we are using the user mention to call the command, we can store just the ID in the database (as my ID doesn't change even if I change my username). Then as a second field we can have a `string[]` to hold the reasons, and return them if the lookup command is called. 

Alternatively, we could have an array of objects (to track the reason and the date).

**Comment by bradtaniguchi** [comment]
I'm trying to think if we should normalize user's into its own collection, or don't do :thinking: 

Since both suspend + userlog commands will reference userIds. Both **could** end up updating the user-names in the DB when the user changes their username to further keep a log of those changes over time. 

I can think of the following schemas with the following properties:
- **user** 
  - userId - could be used instead of the mongoId?
  - currentUserName - could be an array of previous names? Saved on the document with a date?

- **suspensions** 
  - userId - the user affected
  - reason
  - date
  - modId - the id of the mod who reported it (we can also save the mods username at the time here aswell)
  - status - either suspended, or "removed" or similar? This way we can know who is suspended/unsuspended over time. Could also be used to "re-consider" a user who has been suspended for a long period of time, if we close the room maybe?

- **logs**
 - userId - the user affected
 - modId - the id of the mod who reported it (also username maybe?)
 - date

Any thoughts on this setup?

**Comment by naomi-lgbt** [comment]
This one won't be "completed" by the merge of #157 right?

**Comment by bradtaniguchi** [comment]
> This one won't be "completed" by the merge of #157 right?

No, #157 was only **part** of the changes. This issue will need to leverage the changes to the schema and database

**Comment by bradtaniguchi** [comment]
not going to do this due to #202 .
