### ISSUE TITLE
[CHORE] Update repo for hacktoberfest

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#154]
**What needs to be done**
I need to update this repo for contributions for hacktoberfest. 

**Additional context**
see: https://hacktoberfest.digitalocean.com/?utm_medium=email&utm_source=hacktoberfest&utm_campaign=pre-launch_&utm_content=pp

**Comment by naomi-lgbt** [comment]
So this requires: 
- [x] A CONTRIBUTING.md (for contributing guidelines)
- [x] A Code of Conduct
- [x] A `hacktoberfest` label
- [ ] Issues that are good for contributors participating in hacktoberfest

Right? This is what I gathered from reading that link.

**Comment by bradtaniguchi** [comment]
Yup, the last point (issues marked) can be done later, since we have a while until then and I'd rather not label something as it **could** prevent it being done until October haha

**Comment by naomi-lgbt** [comment]
AFAIK, fCC isn't planning on anything specific for Hacktoberfest. I'll go ahead and close this.
