### ISSUE TITLE
[Bug] Fix issue with "invalid user" appearing

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#156]
**Describe the bug**
When the bot reports to the "access restricted" channels the suspended user's mention turns into "invalid user" or a long "id string" if an admins client comes and "looks" at the user message later. (Not 100% sure when this happens, but it happens enough)

**To Reproduce**
General steps to reproduce the behavior:
- go to the admin-log channel after a report has been made on a discord instance **after** it has been a while, where the user mentioned left/go suspended. So for example opening discord in a new tab/browser would make the mentioned user look "weird"

**Expected behavior**
We should just show the user's name as plain text, and maybe keep the mention for reference.

**Additional context**
I'm not 100% sure when this happens, I know it has to deal with the `fetch` method limitations with the discord API, but not sure beyond that. Like does changing the role of the user to the suspended role actually make them no longer appear in the mention in the log? Or is it they leave, or just something else?

**Comment by naomi-lgbt** [comment]
I believe this could be fixed with using the `user.username` value instead of a direct mention. This should only be occurring in instances where the mentioned user has left the server, as Discord can no longer tie the `user` data to the `member` data based on the `id` (because the `member` no longer exists). 

I can submit a fix for this - do we want to roll out a fix immediately, or include it in our DB overhaul?

**Comment by bradtaniguchi** [comment]
Sorry for sandbagging on this. Yea we can make a fix and get it to fix this issue right now. The db overhaul shouldn't be rushed, and this issue is currently a problem in "production" so lets merge it with #158

**Comment by naomi-lgbt** [comment]
Whoops. Forgot to link this with my new PR. This should be fixed now I believe.

**Comment by bradtaniguchi** [comment]
My fault, I put the "close" tag to be the PR, rather than the actual issue (I've done this multiple times in the past)

This issue was closed with:
01295727439f895564a6f46af3ae715f8ad0419e

**Comment by phantom0109** [comment]
![image](https://user-images.githubusercontent.com/92105329/151355236-4d2a069c-9807-4246-8e70-bbfdeec12f1e.png)
I was unable to login to my account

Regards.

**Comment by naomi-lgbt** [comment]
@phantom0109 hey there, while this is a bot built for the Discord platform, we are not able to provide Discord support here. Recommend you reach out to them at https://dis.gd/support if you are having issues.

I've hidden your comment as it contains personal information. 🙂

**Comment by devin-burbach** [comment]
thanks for your support.
