### ISSUE TITLE
[CHORE] Add a github action that manages contributors to the README, or another file 

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#159]
**What needs to be done**
There **has to be** a github action that can automate giving credit to contributors in the README file, or otherwise. 

**Additional context**
Please post here for discussion anything you find before we commit to adding it to a workflow :D

**Comment by naomi-lgbt** [comment]
Man I saw this and got SO excited because I thought we had our hackathon GH Action idea.

But no, [one already exists](https://github.com/marketplace/actions/contribute-list).

**Comment by naomi-lgbt** [comment]
![image](https://user-images.githubusercontent.com/63889819/91471672-3d7cc600-e84b-11ea-9fbc-d255f8fc834a.png)

So this is what the workflow outputs. It seems like a fairly easy set-up, *but* it gets a little more complicated with protected branches. Not sure if the master branch is protected or not. 🤔

**Comment by bradtaniguchi** [comment]
I don't think it is, and probably wont be so we shouldn't have to worry about that.
