### ISSUE TITLE
[CHORE] Migrate from travis-ci to github-actions

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#160]
**What needs to be done**
Currently we are using travis-ci to do a few things automatically. We should migrate to github actions instead.

**Additional context**
I'd like to do this mainly to keep everything in 1 place (github), and also we can leverage open source actions.

Please post here before opening any PR :)

**Comment by Twaha-Rahman** [comment]
I'd like to give a hand in this issue since I'm already juggling with them in fCC's repo for a few days

**Comment by bradtaniguchi** [comment]
Awesome thanks :D

If you can think of other things to "tack on" we can open issues to add those later too (I've been trying to think of easier stuff for beginners to do to help contribute to the bot)

**Comment by LandonLloyd** [comment]
Can I try at it? I am not really sure what needs to be done but I think I can do it with a little explanation.

**Comment by bradtaniguchi** [comment]
@LandonLloyd Your welcome to try it out, I'm seeing us use more github actions in the future, so even if @Twaha-Rahman gets their PR in before you it would be a good learning experience. However, whoever submits a working PR first, will be the one we will merge, since its been a day or so.

Just be sure to have the github-actions working **on your fork**  so we can know if its working or not before merging

**Comment by LandonLloyd** [comment]
Ok. I have no idea what I am doing but I will google and see what I can figure out!

**Comment by bradtaniguchi** [comment]
@LandonLloyd let me know they aren't 100% sure if they can do this, but they are using this issue as a learning experience. In the mean time going to remove them as assigned just in case. 😄 

@Twaha-Rahman any updates on this PR BTW? Now rush, just curious, as I personally like the idea of using github-actions rather than travis-ci, however the migration probably isn't seamless. We also could use **other** workflows, and was just wondering **if you had any ideas of what else to automate in this project? 

(I may open an issue specifically for "brain storming" github-action integration ideas)

**Comment by Twaha-Rahman** [comment]
Sorry @bradtaniguchi , completely forgot about it. 😅

I moved the Linting and Testing part to GitHub Workflows.
