### ISSUE TITLE
[DOCUMENTATION] Update contributing documentation with "First Timers instructions"

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#162]
**Is this request related to a problem? Please describe.**
Besides contributing to the bot itself, those that want to help can always:
- help test
- contribute to documentation
- and open feature requests. 
- add translations (for future multi-lingual support, we don't need to do this yet)

**What could be updated to fix the problem(s)?**
We can add documentation on managing each of these.
1 pr can be opened for all of these at one time, or 1 pr for each section. All should be under a section named "First Timers Instructions" or "First Timers"

**Comment by naomi-lgbt** [comment]
Maybe calling the section "First Timers Welcome" would be encouraging?

**Comment by bradtaniguchi** [comment]
> Maybe calling the section "First Timers Welcome" would be encouraging?

Must better wording! I'll update the original post and title :D

**Comment by LandonLloyd** [comment]
I can work on this one! Is this in the readme? or contribute.md?
