### ISSUE TITLE
[FEATURE] Remove automatic assignees to issue templates, keep them in PR

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#168]
**What needs to be done**
Currently @bradtaniguchi and @nhcarrigan are automatically assigned as Assignees to most it not all issues created. This should be changed, to incentivies **other** user's to contribute to the bot. 😄  This will also fit with the workflow that stuff people work on is assigned to those working on it at that time.

**Additional context**
However the PR template should **keep** these two people as assignees, as they should review any PR's made.

PS. This issue is written in the third person, which is kinda funny haha

**Comment by naomi-lgbt** [comment]
The PR template doesn't actually assign anyone. That's handled by a `CODEOWNERS` file which we don't have - easy enough to add though. 

LHLloyd has been eager to contribute to the bot and this seems like a good place to start. I'll ping him when he's next online and see if he's interested.

**Comment by LandonLloyd** [comment]
I'll look into how to fix this! Thanks guys!!!
