### ISSUE TITLE
Prepare bot for handoff to freeCodeCamp dev team

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/CamperChan-discord#176]
**What needs to be done**

We have received a request to turn over "ownership" of the bot to the freeCodeCamp dev team. In order to make the transition as smooth as possible, we should accomplish the following steps.

- [x] Establish `master` as default branch, `live` as protected deployment branch. 
- [x] Complete the establishment of CI/CD pipeline: PRs pass CI, merge to master, periodically merge master to `live`, Heroku deploy from `live`.
- [ ] Review all outstanding issues and PRs. Complete any urgent ones, close all others. 
- [ ] Work with Mrugesh to transfer repository to freeCodeCamp organisation
- [ ] Work with Mrugesh to transfer ownership of Heroku application
- [ ] Work with Mrugesh to create new Discord Bot application
- [ ] Transfer `env` variables to maintain current bot functionality.

@bradtaniguchi feel free to edit/add as needed.

**Comment by Twaha-Rahman** [comment]
Quick question, I was working on a small PR, would it be wise to do a PR tomorrow? Or should I wait for the migration? 🤔

**Comment by bradtaniguchi** [comment]
> Quick question, I was working on a small PR, would it be wise to do a PR tomorrow? Or should I wait for the migration? thinking

Depends what the PR is

**Comment by Twaha-Rahman** [comment]
> Depends what the PR is

The PR adds a few feature that basically adds embeds for any issue/PR reference when a user types a # followed by the issue/PR number.

**Comment by Twaha-Rahman** [comment]
Here's an example -> https://discord.com/channels/705679411936100416/710976322721284167/751029250219573318

**Comment by bradtaniguchi** [comment]
I think that PR/feature would be able to be fit in, that is part of the "migration from gitter" requirements right?

**Comment by Twaha-Rahman** [comment]
> I think that PR/feature would be able to be fit in, that is part of the "migration from gitter" requirements right?

I believe so.

**Comment by naomi-lgbt** [comment]
Closing this as handed off.
