### ISSUE TITLE
[FEATURE] Update issue/pr link to prevent duplicates of the same issue being linked

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#182]
**Is your feature request related to a problem? Please describe.**
Currently if you mention multiple issues with the same number, the bot links multiple again.

**Describe the solution you'd like**
The bot shouldn't re-link the same issue if it already did, this should help prevent calling the github api too many times.

**Additional context**
Here is what the current bot does:
![Screenshot 2020-09-19 at 13 34 17](https://user-images.githubusercontent.com/10079147/93688743-e4d0cf80-fa7c-11ea-8b2e-c34af41b1b9f.png)

**Comment by Twaha-Rahman** [comment]
I'm on it. I'll submit a PR soon.
