### ISSUE TITLE
[CHORE] Update issues/goals for future

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#202]
**What needs to be done**
Clean up and refocus issues/features in the bot for stability and (still) handoff. 

**Additional context**
- Currently anything related to mongodb will shut off in a few days, but we haven't used any of the database features. So we should remove the DB libs and any commands related to the database.

**Comment by bradtaniguchi** [comment]
Is this still active/important? 

Could close this as all related issues are closed.

**Comment by naomi-lgbt** [comment]
Yep yep

**Comment by bradtaniguchi** [comment]
Could unpin this issue as well 👍🏼
