### ISSUE TITLE
[FEATURE] Remove the "user note" feature

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#203]
**Is your feature request related to a problem? Please describe.**
As part of the migration away from database support, this command needs to be removed as its the last part of the codebase that still connects to the db.

**Additional context**
This command has yet to be used, but can be added in the future. For now, it wont be needed though

**Comment by naomi-lgbt** [comment]
Closing this as resolved in the latest refactor #219
