### ISSUE TITLE
Add editorconfig

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#21]
See:
https://editorconfig.org/

Should match with eslint and prettier settings. Whatever is the common defaults for other repo could be used too.

**Comment by Twaha-Rahman** [comment]
We can integrate Prettier with ESLint without a `.editorconfig` file. See here: https://prettier.io/docs/en/integrating-with-linters.html

**Comment by bradtaniguchi** [comment]
- An `.editorconfig` would be good to add as it would setup rules that are applied when writing/editing code by the editor. Both Prettier and Eslint are there and applied **after** you already wrote/edited the code.

**Comment by Twaha-Rahman** [comment]
Got it! So any prefered rules or formatting style?

(I prefer to have trailing comma disabled.... I don't know why, but I find trailing commas weird)

**Comment by bradtaniguchi** [comment]
Yea I also don't like trailing commas. We can follow something like [FCC's defaults](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/.editorconfig), while tuning anything different to ours.

We can also change prettier/eslint to disallow trailing commas, don't think anyone will mind as long as we stay consistent. 

With travis setup, this should be easier to enforce in PRs aswell.

**Comment by Twaha-Rahman** [comment]
@bradtaniguchi Looks to me like the PR 2bf83d9 closes this issue. If does, can we close this issue?

**Comment by bradtaniguchi** [comment]
This file disappeared somehow, re-opening
