### ISSUE TITLE
Make the help command auto-updating.

### ISSUE THREAD

**Issue by fecty** [freeCodeCamp/CamperChan-discord#22]
Make the `help` command of the bot better, because currently, I assume whenever a new command is programmed, you manually have to add the name and description to the `help` command embed. Instead you can use the library to get all the command names with their description automatically and then iterate through them, appending fields to the embed. But an embed can only have 25 fields, so after each 25 index, you DM whoever invoked the command with the current batch. After that, the fields can be cleared and new command names/description can be added.

**Comment by bradtaniguchi** [comment]
I think we can keep the `help` command under 25 fields even when its dynamic so there wouldn't be a need to send another message or DM. 

We should also update each "command file" to include settings for what will appear in the `help` command.
