### ISSUE TITLE
[chore] Update node version from 12

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#239]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
The current node version specified in `.nvmrc` is beyond support. We should upgrade all the way to the current LTS is `18.x`.

**Comment by naomi-lgbt** [comment]
The VM the bot runs on is using Node 18, so just the file needs to be changed - we should probably add the `engines` field to the `package.json` in the same PR:

```json
"engines": {
  "node": "^18.0.0",
  "npm": "^9.0.0",
}
```

**Comment by bradtaniguchi** [comment]
We can include that, and clean up the libraries when working locally with `nvm`. 👍

**Comment by bradtaniguchi** [comment]
I can pick up this one, but I'll leave #240 as a "good first issue" for someone else.

**Comment by bradtaniguchi** [comment]
Does the gitpod build come with nodejs? Its been a while since I've used it. I forget if ubuntu comes out of the box with nodejs, and if it does its usually an older version. Might create an issue later to include `nvm` installation to gitpod or something similar.

**Comment by naomi-lgbt** [comment]
GitPod comes with the latest Node LTS by default.

**Comment by bradtaniguchi** [comment]
Ok cool, I won't worry about that then 👍
