### ISSUE TITLE
Add a pinned post listing all the requested and experimental feature

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/CamperChan-discord#24]
Currently we are all working on different features without knowing which feature is being worked on by others or which feature ideas have been scraped. It would be of great help if there was a pinned post that not only lists the features but also shows who's working on which feature. This will improve the whole process because this pinned post can act like a **single source of truth**. I have seen this tactic being applied in other projects, for example a React Doc translations projects -

![Image 3](https://user-images.githubusercontent.com/39026437/82059800-58865880-96e8-11ea-81b7-abf04320ecac.png)

**Comment by bradtaniguchi** [comment]
Good idea, I personally would suggest using github issues tracker to know who is working on what. 
I'll try to assign issues to who is working on em, but those who are working need to comment on the issue(s) for what they are working on :)
