### ISSUE TITLE
[chore] Verify dependabot folder works/is relevant?

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#240]
Does the `.dependabot/config.yaml` still work and is relevant? I know its 2 years since its been last touched and I could of sworn github changed how depedabot alerts are integrated.

**Comment by naomi-lgbt** [comment]
That folder can be removed entirely, and replaced with a `renovate.json` file in the root directory with the following content:

```json
{
  "extends": ["github>freecodecamp/renovate-config"]
}
```
