### ISSUE TITLE
[chore] Add unit tests, or remove test from workflow?

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#241]
Currently there is an `npm run test` call in the current workflow, but there are no tests. There is `jest` and `ts-jest` dependencies so maybe it might be time to look back into adding some basic unit tests? 

Or removing these tests could provide some cleanup.

**Comment by naomi-lgbt** [comment]
The bot itself is notoriously hard to test, but we could certainly write some tests for some of the modules and helper functions.

**Comment by bradtaniguchi** [comment]
I'll take a deeper look into how it's currently setup  and do some research on if there are any patterns for unit testing discord bots.

I'll also keep an eye out for code that makes sense to test too, as I'm sure there's plenty that would just be annoying.

**Comment by bradtaniguchi** [comment]
So it looks like there's a number of people out there writing up full mocks to abstract away the API. Long going thread is here for example:
https://github.com/discordjs/discord.js/issues/3576


I don't know enough about how the new discordjs library works to know if mocking how things are working makes sense or not. As such I probably shouldn't be the one to make the determination as I don't know if I could do the work in a timely fashion.

Other example mocks:
https://dev.to/heymarkkop/how-to-implement-test-and-mock-discordjs-v13-slash-commands-with-typescript-22lc

**Comment by naomi-lgbt** [comment]
Yeah, I've considered implementing some mocks for my own bots, but the amount of overhead involved is just too daunting lol

**Comment by a2937** [comment]
I believe you want to use jest as the testing framework?
