### ISSUE TITLE
[chore] Cleanup readme-script.js

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#242]
There seems to be a bunch of syntax related issues with the scripts/readme-script.js file

Might need to make a pass through it to reformat it/clean it up.

**Comment by naomi-lgbt** [comment]
Honestly, that could just be removed. The commands are slash commands now, which are effectively self-documenting. The reaction features were removed in favour of button components.

Readme itself could use a good overhaul tho.

**Comment by bradtaniguchi** [comment]
Will be opening a PR for this one shortly 👍🏼
