### ISSUE TITLE
Add issue templates with proper labels

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/CamperChan-discord#25]
Currently we are creating issues without any guidelines and can't add any labels. We should have issue templates for each of the following scenarios with adequate labels - 

- [x] Feature Request
- [x] Bug Report
- [x] Needs Further Testing
- [x] Feature Improvement

Since @esfectus and !Ameen have some previous experience with bots they can quite easily spot some common pitfalls and suggest us better ways to solve a problem, that we may have not thought about. So `Needs Further Testing` issues can be assigned to them and they can test the commands and other feature to ensure overall quality and spot bugs we have overseen.

(Note: we can use the `Feature Improvement` label to discuss about improvement to already added features)

**Comment by bradtaniguchi** [comment]
Just created a PR with 3 new issue templates, also added new labels:
- feature
- needs testing

See #26

**Comment by bradtaniguchi** [comment]
This should of been fixed with this commit:
9ac7948976b00277299c5480806d6396723b1851
