### ISSUE TITLE
Disable leveling system for staff members

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/CamperChan-discord#257]
**Describe the suggestion**
The leveling system intent is to recognize active members, but there is no need to include staff members in that role, as most of the time, they are active, and they may outshine campers.

Maybe we can add logic after the code below, to ignore use with role of staff. here is [the code](https://github.com/freeCodeCamp/discord-bot/blob/4ba18b261b29608dbdbab6b67cd3c9981ce24f71/src/modules/levelListener.ts#L24-L33)

```ts
    const user =
      (await LevelModel.findOne({ userId: author.id })) ||
      (await LevelModel.create({
        userId: author.id,
        userTag: author.tag,
        points: 0,
        level: 0,
        lastSeen: new Date(Date.now()),
        cooldown: 0,
      }));
 ```
 
 Maybe with excluding the staff members, it will be easier to notice active members in the localization effort, which doesn't have language lead.

**Comment by naomi-lgbt** [comment]
I'm on the fence with this one.

On one hand, it can be discouraging to see that all the active members are staff. But on the other hand, people love the idea of being able to overtake staff members on a leaderboard.

**Comment by Sboonny** [comment]
Good point, now I am on the fence as well 😅.

**Comment by naomi-lgbt** [comment]
I propose we leave it as is - when we generate contributor lists, we can filter out staff accounts as needed.
