### ISSUE TITLE
Can we change "The moderation team have created this private channel..." message?

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/CamperChan-discord#273]
**Request**
Can we change the initial message when a private channel is created?

The current message is:
"The moderation team have created this private channel to discuss something with you."

Can we change it to something more general, for example:
"A private channel was created by [name]. This channel is visible to only you and the moderation team."

**Context**
I think the current message may seem scary at a first glance (seems like you have caused some moderation problems) so I've been limiting the use of PMs to moderation concerns.

However, I want to use PMs to communicate with contributors individually for more casual conversation. For example, helping new contributors who are afraid of asking questions in a public channel, or just asking if they need any help to increase engagement of the contributors.

I also think it's better to use our PM in my use case above, not Discord's DM. Discord's DM is outside of freeCodeCamp server and it can cause moderation problems.

**Comment by naomi-lgbt** [comment]
We can certainly update the text, but we don't want to include the name of the moderator who opened the ticket. We want to present a united front when we open a private channel with a member, and don't want to accidentally cause a member to single out a moderator.

**Comment by sidemt** [comment]
You're right. I agree with you.

Does it look okay if we just removed "by [name]" part?
"A private channel was created. This channel is visible to only you and the moderation team."

**Comment by naomi-lgbt** [comment]
That could work, yes.
