### ISSUE TITLE
[Bug] Prettier's formatting clashing with ESlint

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/CamperChan-discord#28]
**Describe the bug**

Currently the Prettier extension formats the code according to its setting but ESLint doesn't allow some of those changes which gets linted by ESLint. This behavior can't be escaped as Prettier is currently being runned at commits, for which commits have linting issues which in tern fails in the Travis CI tests.

**To Reproduce**
1. Just write a `switch` statement commit it
2. ESLint will lint Prettier's formatting

**Expected behavior**

Prettier's formatting should remove ESLint formatting issues, not create them.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/39026437/82117834-c6885980-9794-11ea-9d28-455fe9d8f10f.png)

**Comment by Twaha-Rahman** [comment]
@bradtaniguchi I'm working on to fix this issue. Expect it to be fixed soon with a PR

**Comment by bradtaniguchi** [comment]
yeah I was slightly worried about this happening, but haven't had time to work on the project itself (works been insane) 

thanks for finding it out and reporting it :D
