### ISSUE TITLE
Add "Thanks" support back

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#30]
**Is your feature request related to a problem? Please describe.**
The previous gitter bot had a "brownie points" feature, which **will not** be replicated due to spam and "gaming the system" issues. However, having a "hollow" version I think would be acceptable. 

**Describe the solution you'd like**
Anytime someone thanks someone else, the bot will "give brownie points" to the other user. This wont actually increase anyone's points or anything, but will bring recognition to those that help others, which was the main goal of the originals.

**Additional context**
~~TDB (I want to add a reference to the originals text/emoji/setup, we will use the same one for this iteration)~~

**edit** finally, here is the original source code for the original message format:
https://github.com/freeCodeCamp/camper-gitter-bot/blob/529cc6e989f2f9661e3dd65d927727c6489c8249/lib/bot/cmds/thanks.js#L49

(I think this is already know, but adding it anyways)

**Comment by naomi-lgbt** [comment]
I've got some code started for this. If anyone else is working on it let me know! :)
