### ISSUE TITLE
Update eslint rules to prevent let, when const will do

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#38]
**Is your feature request related to a problem? Please describe.**
We can write `let` instead of `const` currently, but this isn't neccessary.

**Describe the solution you'd like**
Update eslint rules to prevent using `let` if a `const` will do.

**Additional context**
Docs on possible solution:
https://eslint.org/docs/rules/prefer-const

**Comment by Twaha-Rahman** [comment]
I'll look at it in more details tomorrow.... probably will take some tweaking here and there...

**Comment by bradtaniguchi** [comment]
I can also check it out on my end, so no worries :)
