### ISSUE TITLE
Decrease supported languages for Highlightjs

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#40]
**Is your feature request related to a problem? Please describe.**
After merging #27, the bot will get "confused" between potential language guess more often than not. This is due to the **huge** amount of language support the library has

**Describe the solution you'd like**
After merging #27, the bot will provide 2 guesses for a given language if it can't decide. We can decrease the collision amount by providing only a set list of language options. The list of supported languages should be more or less the same as those that can be formatted by prettier and maybe a few more that are commonly asked for within FCC.

The most common use-case languages will probably be html, css, JS and Python (which isn't supported by Prettier, but is usually readable automatically). We can support a few other ones that prettier supports that I haven't listed.

So we will update the [hljs language set](https://highlightjs.readthedocs.io/en/latest/api.html#highlightauto-code-languagesubset) to be only from a limited set of commonly used languages within the FCC community.

**Additional context**
This should decrease the available "features" the syntax highlighting can recognize, but make the bot easier to use for most of its common use-cases.

**Comment by naomi-lgbt** [comment]
According to the highlight.js docs, [these](https://highlightjs.org/static/demo/) are the common languages - might be worth considering this list? 39 is a lot fewer than 189.

**Comment by Twaha-Rahman** [comment]
I'm working on it.... @bradtaniguchi feel free to assign it to me..
