### ISSUE TITLE
Update README setup flow to include Manage Messages permissions

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#41]
**Is your feature request related to a problem? Please describe.**
After merging #27, anyone who wants to setup the bot and use that command will require special permissions to "Manage Messages", as the bot will "clear" emojis when formatting strings. 

**Describe the solution you'd like**
Update the README with information similar to what was said here: https://github.com/bradtaniguchi/discord-bot-test/pull/27#issuecomment-630631179

We should update the README's step by step docs to include this setting, when adding the bot to a discord server/guild.

**Describe alternatives you've considered**
We could update the bot to not even rely on this permission to make maintaining it simpler.

**Comment by Twaha-Rahman** [comment]
Updating the `Readme` right now.... feel free to assign it to me!
