### ISSUE TITLE
Add Bot Command to Close issues or PRs with a standard message

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/CamperChan-discord#425]
Add a bot command to close issues with the standard message.

**Comment by naomi-lgbt** [comment]
We can refer to the templates for [invalid PRs](https://contribute.freecodecamp.org/#/reply-templates?id=closing-invalid-pull-requests) and [invalid issues](https://contribute.freecodecamp.org/#/reply-templates?id=closing-invalid-issues)
