### ISSUE TITLE
Organize the files in the src/commands by platform

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/CamperChan-discord#440]
The `src/commands` directory could use some love with regards to the organization. It is probably worth creating subdirectories for platforms? For example `close` and `pullComments` are related to GitHub and others are for Discord and so on.

**Comment by naomi-lgbt** [comment]
The file structure maintains parity with the command structure.

That is, if we wanted `close` and `pullComments` under `github`, we'd move them to a `src/commands/gitub.ts` command and turn them into sub-commands.

**Comment by naomi-lgbt** [comment]
As an example of what that might look like: https://github.com/nhcarrigan/becca-lyria/blob/main/src/commands/mod.ts
