### ISSUE TITLE
[Bug] Server crash when user leaves

### ISSUE THREAD

**Issue by magnus195** [freeCodeCamp/CamperChan-discord#47]
**Describe the bug**
When a user leaves, the whole server crashes and needs to be started again

**To Reproduce**
1. Leave the server

**Expected behavior**
Send a leave message to some channel

**Screenshots**
![bilde](https://user-images.githubusercontent.com/22998711/83361722-7cee6000-a38b-11ea-867f-a38eeaa18603.png)

**Comment by naomi-lgbt** [comment]
This bug is due to the fact that the code looks for a channel called "introduction", but the channel in my test server is "introductions" to mirror my personal server.
