### ISSUE TITLE
Add configurable setting for the bot to work in only 1 room

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#49]
**Is your feature request related to a problem? Please describe.**
As part of the testing the bot needs to be able to be limited to listen to only 1 room. This should be done via an optional environment variable IE "contributors"

**Describe the solution you'd like**
Update the config settings to take in a new environment variable "room".

**Additional context**
When nothing is passed, this setting should deactivate and allow the bot to listen to anywhere in the server as before.

**Comment by naomi-lgbt** [comment]
I believe it was recommended to use Discord to allow the bot into specific channels, right? Do we want to try to add this code still?

**Comment by bradtaniguchi** [comment]
So I looked into this a little more, and forgot to update this issue.

It seems like the correct way to handle this is by using server roles, rather than setting anything in the bot code itself. As such I'll close this since this stuff should be managed at the discord server level, rather than the bot level.


[ref](https://support.discord.com/hc/en-us/community/posts/360045778711-Restrict-bots-to-certain-channels-#:~:text=At%20the%20moment%2C%20the%20only,the%20more%20tedious%20it%20becomes.)

[ref](https://www.reddit.com/r/discordapp/comments/5dzw0c/restrict_bot_to_one_text_channel_without_fussing/)
