### ISSUE TITLE
Dramatically update thanks parsing capabilities

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#54]
**Is your feature request related to a problem? Please describe.**
Apparently the original gitter bot's "thanks" command supported multiple languages and even typos.

**Describe the solution you'd like**
We can carry over a similar solution from the original. We should also add the same tests to verify we get the same support as before.

**Additional context**
Here is the regex that was applied, it was slightly hard to find, but I guess this is what was used to check if the message had the command:
https://github.com/freeCodeCamp/camper-gitter-bot/blob/529cc6e989f2f9661e3dd65d927727c6489c8249/data/rooms/RoomMessages.js#L49

**Comment by naomi-lgbt** [comment]
NVM - had the wrong settings.
