### ISSUE TITLE
Screenshot snippet "friendliness"

### ISSUE THREAD

**Issue by plamoni** [freeCodeCamp/CamperChan-discord#557]
Our [current snippet](https://github.com/freeCodeCamp/discord-bot/blob/87d00eca6c1e8bc3639cff86530a569f2ab97335/src/config/Tags.ts#L4-L8) reads:

> Pictures of code are hard to read and cannot be copied into a local IDE for debugging. Please send your actual code or a link to your repository, instead of a picture.

This response could come across as intimidating to people who are band new and might not know what a repository is or how to post a code block on Discord.

I propose we update the language and provide links and be more positive. Proposed update:

> Photos/screenshots of an error can be helpful in diagnosing an issue/bug; however, it also helps to provide the complete source code so that we can debug it locally. You can use a [discord code block](<https://gist.github.com/matthewzring/9f7bbfd102003963f9be7dbcf7d40e51#code-blocks>), [GitHub Gist](<https://gist.github.com/>), [GitHub repository](<https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository>), or [PasteBin](<https://pastebin.com/>). Thanks!

```md
Photos/screenshots of an error can be helpful in diagnosing an issue/bug; however, it also helps to provide the complete source code so that we can debug it locally. You can use a [discord code block](<https://gist.github.com/matthewzring/9f7bbfd102003963f9be7dbcf7d40e51#code-blocks>), [GitHub Gist](<https://gist.github.com/>), [GitHub repository](<https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository>), or [PasteBin](<https://pastebin.com/>). Thanks!
```

Thoughts?

**Comment by kabirgaire0** [comment]
I was on the programming-help channel on freecodecamp.org and a beginner coder was asking a question to a very basic html problem he was having while finishing a step on a learning course on a website. So like every beginner does every time they get stuck, he asked a question with the screenshot. The bot then responded with very difficult words like debugging and repository which no beginner is expected to know. So I hope we could find a way to not scare beginners with those difficult words or maybe make the difficult words into a link that opens up a site with explanation. It would be even better if there was a link you could click in the end of the message that would route people to a site that asks you what your skill level is, and then teach you proper ways of asking questions or ethics or something.

Thanks for reading, hope something clicks in someone's mind or someone gets some ideas from this.

MOD EDIT: converted to proper English from e-girl uwu speak.

**Comment by jeremylt** [comment]
> Photos/screenshots of an error can be helpful, but it also helps to provide the complete  code. Posting the code helps us help you better!

Maybe this simplified wording?

**Comment by plamoni** [comment]
> > Photos/screenshots of an error can be helpful, but it also helps to provide the complete code. Posting the code helps us help you better!
> 
> Maybe this simplified wording?

I want to provide people with links on how they might "post the code," so that it's more actionable. But I'm okay with the other adjustments.

**Comment by jeremylt** [comment]
Yeah, I liked the sentence with the links too

**Comment by plamoni** [comment]
Updated:

> Photos/screenshots of an error can be helpful, but it also helps to provide the complete code. Posting the code helps us help you better!
> 
> You can use a [discord code block](<https://gist.github.com/matthewzring/9f7bbfd102003963f9be7dbcf7d40e51#code-blocks>), [GitHub Gist](<https://gist.github.com/>), [GitHub repository](<https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository>), or [PasteBin](<https://pastebin.com/>).

```
Photos/screenshots of an error can be helpful, but it also helps to provide the complete code. Posting the code helps us help you better!

You can use a [discord code block](<https://gist.github.com/matthewzring/9f7bbfd102003963f9be7dbcf7d40e51#code-blocks>), [GitHub Gist](<https://gist.github.com/>), [GitHub repository](<https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository>), or [PasteBin](<https://pastebin.com/>).
```

**Comment by naomi-lgbt** [comment]
For interested contributors, the line that will need to be updated is here:

https://github.com/freeCodeCamp/discord-bot/blob/87d00eca6c1e8bc3639cff86530a569f2ab97335/src/config/Tags.ts#L7
