### ISSUE TITLE
suggestions in improving the contributing.md docs

### ISSUE THREAD

**Issue by RGHANILOO** [freeCodeCamp/CamperChan-discord#559]
In my earlier attempt in fixing one of the issues, i faced the following challenges which i describe below as a form of updating the contributing.md documentation 

line 25:
  At this point make sure the Developer Mode is enabled in your user settings of Discord
  ```mermaid
  graph LR 
  A(Discord Application) --> B(USER SETTINGS)--> C(APP SETTINGS)--> D(Adanced)--> E(Developer Mode = Enable) 
```
alternatively we could say this at the beginning of the page on line 3  :
`To develop this project locally, you will need to be running [NodeJS v20](https://nodejs.org/en/) , [pnpm v8](https://pnpm.io/). and have enabled Developer Mode in Discord` 

line 40 could be updated to `pnpm i --frozen-lockfile`  or `pnpm install`
`npm ci` refused to work for me showing the following as error
`The npm ci command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.`

line 46 could be updated to `pnpm run build`.
line 73 could be updated to `pnpm start`.
line 83 could be updated to `pnpm run lint`.

**Desktop (please complete the following information):**
 - OS: [MacOS 13.4.1]
 - Browser: [Chrome]
 - Version: [122.0.6261.94 

**Additional context**
I am happy to work on this issue once the correct approach and wording is decided.

**Comment by naomi-lgbt** [comment]
This sounds good.

I think the developer mode comment should go directly before
> Right-click on your Discord server icon (the one in which you'll be running the bot) and select Copy ID. This goes in your .env file as HOME_GUILD.

We could say something like `If you haven't already, enable Developer Mode in your Discord client. Do this by opening your user/account settings, selecting `Advanced`, then toggling `Developer Mode` on.

**Comment by RGHANILOO** [comment]
That's brilliant, Thank you.

are you ok with me updating the commands on lines 40, 46, 73 and 83?
