### ISSUE TITLE
Update docs to go over how to add the bot to only select channels

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#58]
**Is your feature request related to a problem? Please describe.**
During development we will probably only want the bot to be available in certain channels rather than the entire server.
This can be done using discord itself, but this process should be documented.

**Describe the solution you'd like**
Update the README with information on limiting the discord bot to select channels.

**Comment by naomi-lgbt** [comment]
I can refactor this into the docs too.
