### ISSUE TITLE
Grant CamperChan write permissions to some repos

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/CamperChan-discord#587]
CamperChan isn't able to close PRs in some repos:
- https://github.com/freeCodeCamp/boilerplate-demographic-data-analyzer
- https://github.com/freeCodeCamp/boilerplate-medical-data-visualizer
- https://github.com/freeCodeCamp/boilerplate-infosec

While you're at this, please help give her write permissions to the following repos as well (they aren't accepting contributions yet, but just in case):
- https://github.com/freeCodeCamp/contribute
- https://github.com/freeCodeCamp/ui

**Comment by naomi-lgbt** [comment]
@raisedadead would we be able to grant camperbot maintainer permissions across all repos? Or do I need to continue adding the @freeCodeCamp-bot team to repos?

**Comment by raisedadead** [comment]
That is a account, and not a team? There is an @freeCodeCamp/bots team which we could add to all repos.

**Comment by raisedadead** [comment]
The correct solution is to make CamperChan use GitHub Application Credentials, which can then be installed on all repos. Using PAT with the bot accounts is not a good idea IMHO.

**Comment by naomi-lgbt** [comment]
> That is a account, and not a team? There is an @freeCodeCamp/bots team which we could add to all repos.

Whoops yes that's the one I meant to tag

**Comment by naomi-lgbt** [comment]
> The correct solution is to make CamperChan use GitHub Application Credentials, which can then be installed on all repos. Using PAT with the bot accounts is not a good idea IMHO.

Will look in to this

**Comment by naomi-lgbt** [comment]
Closed as completed - she now uses an app and is authed to all repos.
