### ISSUE TITLE
Update stats command to include more information about the bot. 

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#59]
**Is your feature request related to a problem? Please describe.**
When running the `<prefix> stats` command, we should have the reply include more of the following:
- Uptime (time since the bot was started)
- Commit, tag and time the bot was deployed with/on
  - this should be available either from heroku/environment, or to be environment agnostic, available from a JSON file created during build and deployed with the bot itself that is loaded upon startup.

**Describe the solution you'd like**
Update the command with those features, might require updates to travis-ci to do this automatically before/after deployment

**Comment by JoshQuaintance** [comment]
I can implement the Uptime and maybe the commit and tag. I can totally do the time the BOT is deployed at. This should be an easy task to add.

*Note: Do you want these to be a ts file?*

**Comment by bradtaniguchi** [comment]
The `ts` changes aren't merged yet, but this feature shouldn't be reliant on it.

I'd create a script (in js is fine, it can be migrated later) that can be ran via an npm script that gets this information and creates a `json` file at the path of our choice. I'm honestly not sure if this script will be ran in heroku or in travis yet, your welcome to look into when we'd run this beyond just getting the actual git hash

The up-time feature should be vastly easier. If you want to just do that you can open a PR just for that one part, and we can do the commit/tag/time later as it depends on how the deployment/runtime environment.

**Comment by naomi-lgbt** [comment]
As an FYI, I discovered yesterday that Heroku closes and reloads the bot every day, so the uptime will be reset.

**Comment by JoshQuaintance** [comment]
Alright, I'll work on the uptime feature, as of the comit/tag/time, I might need to do some more research on how heroku or travis takes on data. Just for clarification, the uptime is going to rely on discord.js's Client.uptime right?

**Comment by bradtaniguchi** [comment]
> As an FYI, I discovered yesterday that Heroku closes and reloads the bot every day, so the uptime will be reset.

That should be fine, the bot technically will "go down" every half hour or so of not being used on the free tier, so the uptime will be very short with our current setup

**Comment by bradtaniguchi** [comment]
> Alright, I'll work on the uptime feature, as of the comit/tag/time, I might need to do some more research on how heroku or travis takes on data. Just for clarification, the uptime is going to rely on discord.js's Client.uptime right?

Yea that works, I didn't know about `Client.uptime` and would of done it totally manually, but either should work for the feature. Good find! :D

**Comment by JoshQuaintance** [comment]
Does the commit tag means the GitHub Commit hash.

If so, I can do this and even get the "botOnlineAt" function possibly working.

**Comment by bradtaniguchi** [comment]
A git tag is different than a github commit, and since we are using travis-ci for our deployment, the process of getting either might be different than getting it "locally".

I realized we don't use tags at all, so don't worry about getting the tag, just a commit hash (or the short one) would be fine, so we can link up the deployment with a specific commit in git.

**Comment by JoshQuaintance** [comment]
What if we use a package? This one I have tried and it works: https://www.npmjs.com/package/git-repo-info

**Comment by bradtaniguchi** [comment]
That will work if `.git` is available in travis-ci/heroku

**Comment by JoshuaPelealu** [comment]
Just in case it's not available, since the heroku slug compiler removes the `.git` directory, what we can do a script that will get the commit hash after Travis checks and tests, before the deploy. then it will create a simple file using `fs` that contains the information that we need. Then Travis will deploy it to heroku. Just an idea

**Comment by JoshQuaintance** [comment]
Is the bot going to be deployed using git-push? If so, since we're going to use Heroku, there is another approach to this. Using Heroku's `SOURCE_VERSION` variable on Build. So we can create a script that grabs that variable and declare it, then we can grab the value inside the main bot. https://devcenter.heroku.com/changelog-items/630

**Comment by bradtaniguchi** [comment]
Right now we are using travis to deploy to heroku following this example:
https://docs.travis-ci.com/user/deployment/heroku/

here's the config file in this repo:
https://github.com/bradtaniguchi/discord-bot-test/blob/master/.travis.yml

---

If this environment variable is available when we run the bot we can use it instead, but if that variable is only in [heroku pipelines](https://devcenter.heroku.com/articles/pipelines) (not really that clear from the changelog item) then Idk if it would be available at the right time.

**Comment by JoshQuaintance** [comment]
The environment variable `SOURCE_VERSION` is only available during the build process. To grab it, we have to use a bash script and add it as a buildpack to heroku that will run while building the bot. Luckily, somebody else has made a great script that works: https://elements.heroku.com/buildpacks/ianpurvis/heroku-buildpack-version. 
All we have to do is add this to the project as a buildpack, then to get the commit hash just use the `process.env.SOURCE_VERSION`. I personally have tried this on my own bot, and it worked out great.

<hr>
 
We don't need to mess anything with the travis config file, it's just going to be a buildpack tied to the app on heroku

Are we going to display the full commit hash or the shorten version.
