### ISSUE TITLE
Add unit testing setup (jest)

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#6]
Being able to run some tests at **some** level would be useful. Look into setting up [jest](https://jestjs.io/).

Would also need to integrate with: #5

**Comment by Twaha-Rahman** [comment]
@bradtaniguchi I am going to take a look at this today. Feel free to assign it to me😁

**Comment by bradtaniguchi** [comment]
> @bradtaniguchi I am going to take a look at this today. Feel free to assign it to me😁

Awesome! Part of setting this is up is being able to apply it some some code somewhere. So far there isn't a ton of easy opportunities to leverage testing, so having some "fake" tests just to make sure jest+travis is setup properly should be fine :)

**Comment by bradtaniguchi** [comment]
Closed with above PR
