### ISSUE TITLE
Add "coc" command, will bring up a link to the code of conduct for FC in chat

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#60]
**Is your feature request related to a problem? Please describe.**
Referencing the code of conduct isn't very common, but providing it as a link in chat is slightly annoying because a user needs to find it online then copy/paste the url in chat. 

**Describe the solution you'd like**
Adding a new command `<prefix> coc`

**Describe alternatives you've considered**
We could return the contents of the coc as is, but this will require upkeep if the coc ever changes. Better to provide a link so its easier to reference in the future for all parties.

**Additional context**
We might want to make the URL an environment variable or put into a constant file for easier changes down the line?

**Comment by naomi-lgbt** [comment]
I will take a look at implementing this tonight. 🙂
