### ISSUE TITLE
Add "format" command

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#66]
**Is your feature request related to a problem? Please describe.**
Due to changes with the "reaction" code format feature, the bot will be more aggressive on auto-guessing the language. To provide a more "end-user" version that will provide more support for different languages and potential prettier support

**Describe the solution you'd like**
Add a new command `<prefix> format <message_link> <language>` command that will take a given message contents, the code in that message and try to format+apply syntax highlighting to that message.

**Describe alternatives you've considered**
This can use some of the existing utilities for the :robot: code format feature.

**Additional context**
Prettier should only be applied if the language given is actually recognized by prettier, otherwise don't try to format the code.

**Comment by naomi-lgbt** [comment]
Are we holding off on this until after TS migration?

**Comment by bradtaniguchi** [comment]
> Are we holding off on this until after TS migration?

Yea, I'd even hold off of this until the #65 is also merged too, since I'm sure we can re-use some of the code there

**Comment by Twaha-Rahman** [comment]
Does this mean we are removing the 🤖 code format feature? Or are we simply adding this new feature so that the user can specify the language themselves?

Whichever is the case, I'd like to work on this feature!😊

**Comment by nhcarrigan** [comment]
Neither. The idea is to remove the confirmation message, and just go with the first guess automatically. 🙂

**Comment by naomi-lgbt** [comment]
@Twaha-Rahman Issue #65 has us removing the confirmation message and just going with the first guess automatically. Still using the 🤖 reaction.

Once that's done, we will implement this change to add a format command that allows the user to target the message via the link and pass the specific language (in case the first guess is wrong). 🙂

**Comment by Twaha-Rahman** [comment]
Hmmm... that makes more sense. I think we should do some checks with different sort of codes to see how accurately it detects a language. What do you say?

**Comment by naomi-lgbt** [comment]
The quick checks we ran seemed pretty accurate. The main issue we ran in to was HTML code containing JS script elements. I think the plan there is to have it default to XML if it guesses HTML and JS or HTML and CSS

But if you've got more testing or better suggestions, please share! 🙂
