### ISSUE TITLE
Author info not shown on message reports

### ISSUE THREAD

**Issue by plamoni** [freeCodeCamp/CamperChan-discord#665]
**Describe the bug**
I've noticed that CamperChan doesn't show author information on message reports. This can be a little annoying after a message has been deleted or acknowledged because it's not clear who the author of that message was.

**To Reproduce**
1. Report a message
2. View the message report

**Expected behavior**

I expect it to [show information on the author of the reported post](https://github.com/freeCodeCamp/camperchan/blob/d8cb0d767c53d65368fa6825e6429104caedff58/src/contexts/report.ts#L60-L74).

**Screenshots**

![image](https://github.com/user-attachments/assets/31ae6c05-4118-4f48-bc4f-6ba95881bec5)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
It seems like we're trying to show the author info, but it's not showing for whatever reason. @naomi-lgbt may instantly spot what's up. But my next steps would be to add a few debugging statements in [`report.ts`](https://github.com/freeCodeCamp/camperchan/blob/d8cb0d767c53d65368fa6825e6429104caedff58/src/contexts/report.ts) and see whether the problem is the embed API or the values we're trying to set.

**Comment by naomi-lgbt** [comment]
A note to myself to look at this in the morning.

And to update the embed edit logic too.
