### ISSUE TITLE
Contributing Guide out of date?

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/CamperChan-discord#675]
I am working on #674 but getting linting errors. Following the contributing guide I could not manage to set this up locally on my masOS system - will provide details if needed.

There is no sample env files like the guide says and the `npm run lint` results in 179 errors on the main branch. Am I missing something obvious?

**Comment by naomi-lgbt** [comment]
Yeah, it's likely woefully out of date.

Linter is probably failing because the command instructs you to use `npm`, when it should be using `pnpm`. 

I should be able to get around to updating it this weekend.
