### ISSUE TITLE
Add "suspend" action for moderators

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#69]
**Is your feature request related to a problem? Please describe.**
Currently FCC mods handle suspended users via DMs, this needs to change as Discord DMs are easily disabled, making moderating users hard.

**Describe the solution you'd like**
- [ ] Moderator does command: `!suspend <user> "<reason>" "<evidence>"`
  - [ ] this action should be logged into the `LOG_MSG_CHANNEL`  automatically
- [ ] Bot gives the user the Suspended role
- [ ] Bot writes the report and puts it into #admin
- [ ] Bot creates a private channel only accessible by the suspended user and staff
- [ ] (optionally) Bot DM's the user about being Suspended and that a private channel has been created for them
- [ ] After the situation has been dealt with: !close to close that channel
Moderators can remove the Suspended role and / or ban the user depending on the outcome themselves. The bot doesn't have to get involved with that

**Additional context**
@nhcarrigan said he already has most of these features figured out on his own bot

**Comment by naomi-lgbt** [comment]
I've got the following features on my own bot currently:
- [x] Moderator does command
- [x] Bot assigns role
- [x] Bot sends embed report to `LOG_MSG_CHANNEL`

Will start working on migrating those features to this codebase and adding new features as requested.
