### ISSUE TITLE
Add previous suspension feature

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/CamperChan-discord#73]
**Is your feature request related to a problem? Please describe.**
I received a request from Bjorno on Discord that we allow the suspend command to track if a user has previously been suspended. If the user has previously been suspended, the bot should continue with the command as normal (suspend user, create suspended channel, etc.) but should also DM the admin that calls the command to notify them of a prior suspension.

**Describe the solution you'd like**
I have some additional code prepared for this, but my solution requires a MongoDB connection and a Mongoose dependency. As the suspend command itself is currently still being developed, I thought it best to hold off on this feature until those kinks are worked out.

**Comment by bradtaniguchi** [comment]
We can work on this one together after the migration to TS.

Did you use base mongodb, or mongoose? Once we integrate a database for the bot, it opens up a number of doors for other features. I can't think of any right now that we would want, but its something to think about. 

Also I'm going to add a new label for "db" related stuff

**Comment by JoshuaPelealu** [comment]
Wait, can't it just use a simple `fs` function to create a new file of everyone that has been suspended before? Then use `fs` again to access it to check if they have the property or not.

**Comment by naomi-lgbt** [comment]
I had used mongoose for this - which is compatible with TS and works well on my personal bot. 
Had to create interfaces for the Schemas though (as extensions to the Document).
