### ISSUE TITLE
Add "self pin" feature

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#78]
**Is your feature request related to a problem? Please describe.**
Currently there is a way for admins/mods to pin messages to a channel using the pin message feature. However normal users that would like to "bookmark" or keep track of posts aren't able to.

**Describe the solution you'd like**
We should add a "reaction" feature to a message that works similar to the "format" reaction feature, where if a user adds a "pin" feature, (the one that looks like a red tac) the bot takes that message, copies its contents, and DM's it to the user who pinned it, and then remove its reaction (so other users may pin the message or similar)

**Describe alternatives you've considered**
I'm not sure if the bot should wrap the original message in an embed, or just send it as it without any context.

**Additional context**
This should be done after the migration to TS #55

**Comment by cjcanlas01** [comment]
Can I help with this?

**Comment by bradtaniguchi** [comment]
@cjcanlas01 Yea your welcome to tackle this, just give me until tomorrow (ended up busy today) to finalize the migration to TS and fix a few tiny issues here and there so once #55 is merged, your welcome to add it. :)
