### ISSUE TITLE
Add support to manage previously suspended users if needed

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#90]
**Is your feature request related to a problem? Please describe.**
Currently with the #79 feature, after a user is suspended, we save them to the database. After which we no longer have any visibility or information on who has been suspended.

**Describe the solution you'd like**
We could take multiple approaches to this problem
- Could provide another command to get who is suspended, which is limited by Discords character limits.
- Could provide a way for admins to get who is suspended by their name/id/search to get information on who has been suspended in the past
- Could provide general metrics on who has been suspended (like the number of people suspended)
- Could match/align suspended users with those under the suspended role.

**Additional context**
Should discuss what approach could and should be taken, before starting anything :)

**Comment by naomi-lgbt** [comment]
I'd take the approach where an admin uses a `user <@username>` command and the bot returns an embed stating whether the user has been previously suspended or not.

This allows us to upscale - the command could be expanded to include the certification-based roles the user has, for example.
