### ISSUE TITLE
Add "fun-fact"/trivia command

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#91]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Have a new `fact` or `trivia` command that spits out some random facts. Similar to the quotes from the FCC site.

**Describe alternatives you've considered**
None.

**Additional context**
This **might** add to spam. Will need to think about it.

**Comment by naomi-lgbt** [comment]
I can write the code if you provide the facts. 🙃

**Comment by bradtaniguchi** [comment]
Just thought about something, why not change this feature from trivia to **directly using the same quotes FCC uses**?

We could directly "hijack" the list as-is from the other repo via a web-call thru github **maybe**

**Comment by naomi-lgbt** [comment]
Using the quotes would be cool - change the command from "trivia" to "motivate", maybe?

But, would it be faster to just copy the file to this repo? Otherwise we have to wait for the web-call to resolve?

**Comment by bradtaniguchi** [comment]
the web-call can be done on initial bot load, same way the DB call is made. This will cut down on how much we ping github to only be done when the bar is started/restarted. This way if FCC adds more quotes, the bot will get them automatically on restart

(we could also call every day or something to keep updated, but we can do that later).
