### ISSUE TITLE
Create utility script prints out markdown specifications for commands

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#94]
**Is your feature request related to a problem? Please describe.**
Right now the README lacks any information on what commands are available. 

**Describe the solution you'd like**
 We should create a [markdown table](https://docs.github.com/en/github/writing-on-github/organizing-information-with-tables) to display the list of commands. We can use the **same** command-def definitions from the files via a script that can be ran. 

This will allow us to keep the README in-line with the commands in a well formatted manor that is easy to upkeep.

**Additional context**
This should be done to support **most** of the command features available. Other commands/features like the "pin message" feature should be specified elsewhere in another table (this will be done later, once these commands are refactored)

**edit** it **may** be possible to run an automated check to make sure if all commands are included in the table in travis-ci, but I'm not sure if it could be used to actually keep it updated since it needs to be comited. We can look into this after this feature is actually working.

**Comment by JoshQuaintance** [comment]
I'll do this one. It might even be a good idea to make a documentation page for it with more details in it than inside the repo as a README file.

**Comment by JoshQuaintance** [comment]
Would the script need to be inside the `utillities` folder inside the source?

**Comment by bradtaniguchi** [comment]
> Would the script need to be inside the `utillities` folder inside the source?

I'd name it either `utils` or `scripts`. 

Write the script in **TypeScript** as well, and we can run it using `ts-node`. If you have some stuff working/setup, but then it isn't working you can always open a draft PR **or** link your fork/repo here and ask for help with the tooling/code :)
