### ISSUE TITLE
Refactor how non-command features are handled to be "abstracted" away.

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#95]
**Is your feature request related to a problem? Please describe.**
Right now there are a few "non-command" that work on "emojis". 

**Describe the solution you'd like**
These commands should be abstracted away in a similar manor as the command-def interface. Together this should allow us to update the `help` command to include information for these commands.

**Additional context**
This is related to #94 but should be done at its own pace, as this requires code changes directly in the bot itself.

**Comment by naomi-lgbt** [comment]
You're talking about things like the "thank" and "format" features, right? Where there's not a specific command that's called, but rather the bot is listening for the specific event?

**Comment by bradtaniguchi** [comment]
`thank` is special, in that it reads **all** messages looking for a pattern, I think manually updating the README for that message would make the most sense, or hard-coding it into the table generator.

There are currently 2 "reaction" based features (pin message, and format code) which can be abstracted away, as we probably will be adding other "reaction" based features in the future.
